### ISSUE TITLE
parms fetch might not work without sso_start_url and fish

### ISSUE THREAD

**Issue by w-h-a** [icevans/parms#1]
Hey! Long-time-follower, first-time-poster. 

## What are you trying to do?
Trying to do `parms fetch`.

## What did you expect to happen?
I expect to not get an error suggesting that I need `sso_start_url` in my .aws/config.

## What happens instead?
```fish
Error: unhandled error

Caused by: 
0: dispatch failure 
1: other
2: the credentials provider was not properly configured
3: ProfileFile provider could not be build: profile `nprinfrasso` was not defined: `sso_start_url` was missing
```

## Additional Info

I tried manually adding a `sso_start_url` and got a different error suggesting there was an error loading creds. Works fine on my computer where I have `.aws/credentials`!

**Comment by icevans** [comment]
Can you share your config file? It should work fine with SSO provided `sso_start_url` is set.
